# Generated by Django 5.0.6 on 2024-06-23 19:16

import django.db.models.deletion
import myfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField(verbose_name='晋升日期')),
            ],
            options={
                'verbose_name': 'promotion record',
                'verbose_name_plural': 'promotion records',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='公司名称')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='公司简称')),
                ('superior_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='上级公司')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['company_id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='所属公司')),
                ('superior_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['department_id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('status', models.CharField(choices=[('A', 'Active Status'), ('D', 'Disactive Status')], default='A', max_length=1, verbose_name='状态')),
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='工号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('id_card_number', models.CharField(blank=True, max_length=22, null=True, unique=True, verbose_name='身份证号码')),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True, verbose_name='性别')),
                ('phone_number', models.CharField(blank=True, max_length=70, null=True, verbose_name='联系电话')),
                ('native_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='籍贯')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系地址')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('job_position', models.CharField(blank=True, default='未定岗位', max_length=100, null=True, verbose_name='岗位')),
                ('employee_status', models.CharField(choices=[('A', 'Active'), ('D', 'Dimission'), ('R', 'Retired')], default='A', max_length=1, verbose_name='员工状态')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职时间')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('hr_document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='人事资料编号')),
                ('bank_name', models.CharField(blank=True, choices=[('BPI', 'Bank of the Philippine Islands'), ('BDO', 'Banco de Oro'), ('METRO', 'Metrobank'), ('PNB', 'Philippine National Bank'), ('LANDBANK', 'Land Bank of the Philippines'), ('UCPB', 'United Coconut Planters Bank'), ('DBP', 'Development Bank of the Philippines'), ('RCBC', 'Rizal Commercial Banking Corporation'), ('SECURITY', 'Security Bank'), ('EASTWEST', 'EastWest Bank'), ('CHINA', 'China Bank'), ('HSBC', 'HSBC'), ('CITI', 'Citibank'), ('PNB', 'Philippine National Bank'), ('OTHERS', 'Others'), ('CZB', 'China Zheshang Bank')], max_length=100, null=True, verbose_name='开户行')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='开户行账号')),
                ('employment_type', models.CharField(choices=[('FT', 'Full-time'), ('IN', 'Intern'), ('PB', 'Probation'), ('RH', 'Re-hire'), ('CP', 'Cooperator')], default='FT', max_length=50, verbose_name='用工形式')),
                ('contract_term', models.DurationField(blank=True, null=True, verbose_name='合同期限')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='劳动合同到期时间')),
                ('ss_start_date', myfields.MonthField(blank=True, null=True, verbose_name='社保始缴月')),
                ('hf_start_date', myfields.MonthField(blank=True, null=True, verbose_name='公积金始缴月')),
                ('ss_record', models.TextField(blank=True, null=True, verbose_name='社保始缴记录')),
                ('hf_record', models.TextField(blank=True, null=True, verbose_name='公积金始缴记录')),
                ('record_in_jijian', models.BooleanField(default=True, verbose_name='是否通过极简')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='毕业专业')),
                ('graduate_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='毕业学校')),
                ('graduate_time', models.DateField(blank=True, null=True, verbose_name='毕业时间')),
                ('education_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='文化程度')),
                ('highest_degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='最高学历')),
                ('tech_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='职称')),
                ('tech_title_time', models.DateField(blank=True, null=True, verbose_name='职称取得时间')),
                ('register_certification', models.TextField(blank=True, null=True, verbose_name='注册类')),
                ('qualification_certification', models.TextField(blank=True, null=True, verbose_name='资格类')),
                ('in_labour_union_member', models.BooleanField(default=True, verbose_name='是否为工会会员')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='紧急联系人姓名')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=15, null=True, verbose_name='紧急联系人与本人关系')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='紧急联系人电话')),
                ('political_affiliation', models.CharField(blank=True, max_length=50, null=True, verbose_name='政治面貌')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', myfields.CreateTime(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified', myfields.LastModified(auto_now=True, verbose_name='最后修改时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='公司')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department', verbose_name='部门')),
                ('modifier', myfields.Modifier(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
    ]
