# Generated by Django 5.0.6 on 2024-06-12 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField(verbose_name='晋升日期')),
            ],
            options={
                'verbose_name': 'promotion record',
                'verbose_name_plural': 'promotion records',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='公司名称')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='公司简称')),
                ('superior_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='上级公司')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['company_id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='所属公司')),
                ('superior_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['department_id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('id_card_number', models.CharField(blank=True, max_length=22, null=True, unique=True, verbose_name='身份证号码')),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True, verbose_name='性别')),
                ('phone_number', models.CharField(blank=True, max_length=70, null=True, verbose_name='联系电话')),
                ('native_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='籍贯')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系地址')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Dimission'), ('R', 'Retired')], default='A', max_length=1, verbose_name='员工状态')),
                ('job_position', models.CharField(blank=True, default='无岗', max_length=100, null=True, verbose_name='岗位')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职时间')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('hr_document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='人事资料编号')),
                ('bank_name', models.CharField(blank=True, choices=[('BPI', 'Bank of the Philippine Islands'), ('BDO', 'Banco de Oro'), ('METRO', 'Metrobank'), ('PNB', 'Philippine National Bank'), ('LANDBANK', 'Land Bank of the Philippines'), ('UCPB', 'United Coconut Planters Bank'), ('DBP', 'Development Bank of the Philippines'), ('RCBC', 'Rizal Commercial Banking Corporation'), ('SECURITY', 'Security Bank'), ('EASTWEST', 'EastWest Bank'), ('CHINA', 'China Bank'), ('HSBC', 'HSBC'), ('CITI', 'Citibank'), ('PNB', 'Philippine National Bank'), ('OTHERS', 'Others'), ('CZB', 'China Zheshang Bank')], max_length=100, null=True, verbose_name='开户行')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='开户行账号')),
                ('employment_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('IN', 'Intern'), ('CO', 'Contractual'), ('FL', 'Freelance'), ('OT', 'On-Training')], default='FT', max_length=50, verbose_name='用工形式')),
                ('contract_term', models.DurationField(blank=True, null=True, verbose_name='合同期限')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='劳动合同到期时间')),
                ('social_security_start_date', models.DateField(blank=True, null=True, verbose_name='社保始缴日')),
                ('housing_fund_start_date', models.DateField(blank=True, null=True, verbose_name='公积金始缴日')),
                ('record_in_jijian', models.BooleanField(default=True, verbose_name='是否通过极简')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='毕业专业')),
                ('graduate_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='毕业学校')),
                ('education_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='文化程度')),
                ('highest_degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='最高学历')),
                ('in_labour_union_member', models.BooleanField(default=True, verbose_name='是否为工会会员')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='紧急联系电话')),
                ('political_affiliation', models.CharField(blank=True, max_length=50, null=True, verbose_name='政治面貌')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='公司')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department', verbose_name='部门')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
    ]
