# Generated by Django 5.0.6 on 2024-06-23 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.position', verbose_name='岗级'),
        ),
        migrations.CreateModel(
            name='ActiveEmployee',
            fields=[
            ],
            options={
                'verbose_name': 'Active Employee',
                'verbose_name_plural': 'Active Employees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
        migrations.CreateModel(
            name='DimissionEmployee',
            fields=[
            ],
            options={
                'verbose_name': 'Dimission Employee',
                'verbose_name_plural': 'Dimission Employees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
        migrations.CreateModel(
            name='InternEmployee',
            fields=[
            ],
            options={
                'verbose_name': 'Intern Employee',
                'verbose_name_plural': 'Intern Employees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
        migrations.AddField(
            model_name='promotionrecord',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='员工'),
        ),
    ]
