# Generated by Django 5.0.6 on 2024-06-12 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('FT', 'Full-time'), ('IN', 'Intern'), ('PB', 'Probation'), ('RH', 'Re-hire'), ('CP', 'Cooperator')], default='FT', max_length=50, verbose_name='用工形式'),
        ),
    ]
