# Generated by Django 5.0.6 on 2024-06-23 19:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('name', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='岗级')),
                ('ensure_salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='基本工资')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='月薪基数')),
                ('type', models.CharField(choices=[('m', 'Management Position'), ('p', 'Technocrat Position')], default='m', verbose_name='岗位类型')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
            },
        ),
        migrations.CreateModel(
            name='SalaryRule',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.company', verbose_name='公司')),
                ('super_meal_subsidy', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='驻场餐补')),
                ('normal_meal_subsidy', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='普通餐补')),
                ('social_security_company_bear_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='公司承担社保基数')),
                ('social_security_company_rate', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='公司缴纳社保费率%')),
                ('social_security_self_rate', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='个人缴纳社保费率%')),
                ('provident_fund_company_bear_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='公司承担公积金基数')),
                ('provident_fund_company_rate', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='公司缴纳公积金费率%')),
                ('provident_fund_self_rate', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='个人缴纳公积金费率%')),
                ('labor_union_fee_self_rate', models.DecimalField(decimal_places=7, default=0.0, max_digits=9, verbose_name='个人缴纳工会费率%')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': 'Salary Rule',
                'verbose_name_plural': 'Salary Rule',
            },
        ),
        migrations.CreateModel(
            name='SalaryProcess',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='编号')),
                ('month', models.CharField(max_length=7, verbose_name='生效月份')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='生成时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('status', models.CharField(choices=[('E', 'Entering'), ('C', 'Checking'), ('P', 'Paying'), ('L', 'Locked')], default='E', max_length=1, verbose_name='状态')),
                ('employees', models.ManyToManyField(blank=True, to='employee.employee', verbose_name='员工列表')),
            ],
            options={
                'verbose_name': 'Salary Process',
                'verbose_name_plural': 'Salary Process',
            },
        ),
        migrations.CreateModel(
            name='SocialSecurityProvidentFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_security_base_self_declare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='个人申报社保基数')),
                ('provident_fund_base_self_declare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='个人申报公积金基数')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': 'Social Security Provident Fund',
                'verbose_name_plural': 'Social Security Provident Fund',
            },
        ),
        migrations.CreateModel(
            name='StdSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary_coefficient', models.DecimalField(decimal_places=7, default=1.0, max_digits=11, verbose_name='月薪调整系数')),
                ('meal_subsidy_plan', models.CharField(choices=[('S', 'Super'), ('M', 'Normal'), ('N', 'None')], default='M', max_length=1, verbose_name='餐补计划')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': 'Standard Salary',
                'verbose_name_plural': 'Standard Salary',
            },
        ),
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_item', models.CharField(max_length=50, verbose_name='所得项目')),
                ('income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='本期收入')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='税额')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('effective_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryprocess', verbose_name='薪酬表')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '税务记录',
                'verbose_name_plural': '税务记录',
            },
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('base_salary_coefficient', models.DecimalField(decimal_places=7, max_digits=11, null=True, verbose_name='月薪调整系数')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='月薪基数')),
                ('std_salary', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='定岗满勤标准月薪')),
                ('std_ensured_salary', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='定岗月基本工资')),
                ('std_merit_salary', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='定岗月基本绩效工资')),
                ('no_salary_leave_deduction', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='非带薪请假扣款')),
                ('salary_increase', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='调整增加项')),
                ('salary_decrease', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='调整减少项')),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='当月月薪合计')),
                ('meal_subsidy', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='餐补')),
                ('other_subsidy', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='其他福利')),
                ('total_subsidy', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='当月福利合计')),
                ('salary_before_assessment', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='考核前当月薪酬')),
                ('attendance_deduction', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='考勤考核绩效扣款')),
                ('assessment_increase', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='考核绩效增加项')),
                ('assessment_decrease', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='考核绩效减少项')),
                ('total_salary_before_tax_and_fee', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='当月应发薪酬')),
                ('social_security_provident_fund_self_bear', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='个人承担超额缴纳部分')),
                ('total_salary_for_tax_calc', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='当月计税薪酬')),
                ('fee_self_bear', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='代扣代缴费用')),
                ('tax_self_bear', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='代扣个税')),
                ('total_salary_after_tax', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='当月税后薪酬')),
                ('increase_after_tax', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='税后增加项')),
                ('decrease_after_tax', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='税后减少项')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='员工')),
                ('effective_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryprocess', verbose_name='生效薪酬表')),
            ],
            options={
                'verbose_name': 'Salary Detail',
                'verbose_name_plural': 'Salary Detail',
                'unique_together': {('employee', 'effective_process')},
            },
        ),
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('I', 'Increase'), ('D', 'Decrease')], max_length=1, verbose_name='调整方向')),
                ('adjustment_type', models.CharField(choices=[('I', 'Initial Salary'), ('S', 'Subsidy'), ('A', 'Assessment'), ('T', 'After Tax')], max_length=1, verbose_name='调整类型')),
                ('description', models.CharField(max_length=255, verbose_name='调整内容')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='员工')),
                ('effective_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryprocess', verbose_name='生效薪酬表')),
            ],
            options={
                'verbose_name': 'Salary Adjustment',
                'verbose_name_plural': 'Salary Adjustments',
                'unique_together': {('employee', 'effective_process', 'description')},
            },
        ),
        migrations.CreateModel(
            name='IncomeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_tax_base', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='个税起征点')),
                ('income_tax_rate', models.DecimalField(decimal_places=7, max_digits=9, null=True, verbose_name='个税税率')),
                ('income_tax_quick_deduction', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='个税速算扣除数')),
                ('income_tax', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='个税')),
                ('income_tax_deduction', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='个税扣款')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='员工')),
                ('effective_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryprocess', verbose_name='生效薪酬表')),
            ],
            options={
                'verbose_name': 'Income Tax',
                'verbose_name_plural': 'Income Tax',
                'unique_together': {('employee', 'effective_process')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_work_days', models.IntegerField(null=True, verbose_name='全勤天数')),
                ('work_days', models.IntegerField(null=True, verbose_name='出勤天数')),
                ('late_times', models.IntegerField(null=True, verbose_name='迟到次数')),
                ('early_leave_times', models.IntegerField(null=True, verbose_name='早退次数')),
                ('punch_in_missing_times', models.IntegerField(null=True, verbose_name='上班缺卡次数')),
                ('punch_out_missing_times', models.IntegerField(null=True, verbose_name='下班缺卡次数')),
                ('absent_times', models.IntegerField(null=True, verbose_name='旷工天数')),
                ('no_salary_leave_duration', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='事假')),
                ('illness_leave_duration', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='病假')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='员工')),
                ('effective_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryprocess', verbose_name='生效薪酬表')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'unique_together': {('employee', 'effective_process')},
            },
        ),
    ]
