# Generated by Django 5.0.6 on 2024-06-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_salarydetail_adjustment_after_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsecurityprovidentfund',
            name='provident_fund_base_self_declare',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='个人申报公积金基数'),
        ),
        migrations.AlterField(
            model_name='socialsecurityprovidentfund',
            name='social_security_base_self_declare',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='个人申报社保基数'),
        ),
    ]
