# Generated by Django 5.0.6 on 2024-06-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_created_at_employee_last_modified_and_more'),
        ('salary', '0003_alter_socialsecurityprovidentfund_provident_fund_base_self_declare_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialsecurityprovidentfund',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='socialsecurityprovidentfund',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', unique=True, verbose_name='员工'),
        ),
        migrations.RemoveField(
            model_name='socialsecurityprovidentfund',
            name='effective_process',
        ),
    ]
