# Generated by Django 5.0.6 on 2024-06-12 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_created_at_employee_last_modified_and_more'),
        ('salary', '0005_alter_salaryadjustment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryadjustment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='socialsecurityprovidentfund',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='员工'),
        ),
    ]
