# Generated by Django 5.0.6 on 2024-06-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_remove_attendance_meal_subsidy_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsecurityprovidentfund',
            name='provident_fund_additional_amount_self_bear',
        ),
        migrations.RemoveField(
            model_name='socialsecurityprovidentfund',
            name='provident_fund_amount_company_bear',
        ),
        migrations.RemoveField(
            model_name='socialsecurityprovidentfund',
            name='provident_fund_amount_self_declare',
        ),
        migrations.RemoveField(
            model_name='socialsecurityprovidentfund',
            name='social_security_additional_amount_self_bear',
        ),
        migrations.RemoveField(
            model_name='socialsecurityprovidentfund',
            name='social_security_amount_company_bear',
        ),
        migrations.RemoveField(
            model_name='socialsecurityprovidentfund',
            name='social_security_amount_self_declare',
        ),
        migrations.AlterField(
            model_name='socialsecurityprovidentfund',
            name='provident_fund_base_self_declare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='个人申报公积金基数'),
        ),
        migrations.AlterField(
            model_name='socialsecurityprovidentfund',
            name='social_security_base_self_declare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='个人申报社保基数'),
        ),
    ]
