# Generated by Django 5.0.6 on 2024-06-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0009_remove_socialsecurityprovidentfund_provident_fund_additional_amount_self_bear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydetail',
            name='other_salary_deduction',
        ),
    ]
