# Generated by Django 5.0.6 on 2024-06-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_remove_salarydetail_other_salary_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydetail',
            name='rental_subsidy',
        ),
        migrations.RemoveField(
            model_name='salarydetail',
            name='weather_subsidy',
        ),
    ]
