# Generated by Django 5.0.6 on 2024-06-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0011_remove_salarydetail_rental_subsidy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydetail',
            name='other_assessment_deduction',
        ),
    ]
