# Generated by Django 5.0.6 on 2024-06-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0012_remove_salarydetail_other_assessment_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydetail',
            name='adjustment_after_tax',
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='decrease_after_tax',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='税后减少项'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='increase_after_tax',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='税后增加项'),
        ),
    ]
