# Generated by Django 5.0.6 on 2024-06-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0013_remove_salarydetail_adjustment_after_tax_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'position', 'verbose_name_plural': 'positions'},
        ),
        migrations.AlterModelOptions(
            name='salaryadjustment',
            options={'verbose_name': 'Salary Adjustment', 'verbose_name_plural': 'Salary Adjustments'},
        ),
    ]
