# Generated by Django 5.0.6 on 2024-06-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0014_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='position',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='salaryadjustment',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='socialsecurityprovidentfund',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='stdsalary',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.DeleteModel(
            name='Subsidy',
        ),
    ]
