# Generated by Django 5.0.6 on 2024-06-13 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_created_at_employee_last_modified_and_more'),
        ('salary', '0015_attendance_last_update_position_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydetail',
            name='base_salary_coefficient',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True, verbose_name='月薪调整系数'),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='labor_union_fee_self_rate',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=9, verbose_name='个人缴纳工会费率%'),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='provident_fund_company_rate',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='公司缴纳公积金费率%'),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='provident_fund_self_rate',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='个人缴纳公积金费率%'),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='social_security_company_rate',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='公司缴纳社保费率%'),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='social_security_self_rate',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='个人缴纳社保费率%'),
        ),
        migrations.AlterField(
            model_name='stdsalary',
            name='base_salary_coefficient',
            field=models.DecimalField(decimal_places=7, default=1.0, max_digits=11, verbose_name='月薪调整系数'),
        ),
        migrations.CreateModel(
            name='IncomeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_tax_base', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='个税起征点')),
                ('income_tax_rate', models.DecimalField(decimal_places=7, max_digits=9, null=True, verbose_name='个税税率')),
                ('income_tax_quick_deduction', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='个税速算扣除数')),
                ('income_tax', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='个税')),
                ('income_tax_deduction', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='个税扣款')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('effective_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryprocess', verbose_name='生效工资条')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': 'Income Tax',
                'verbose_name_plural': 'Income Tax',
                'unique_together': {('employee', 'effective_process')},
            },
        ),
    ]
