# Generated by Django 5.0.6 on 2024-06-13 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0016_alter_salarydetail_base_salary_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadjustment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='effective_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryprocess', verbose_name='生效薪酬表'),
        ),
        migrations.AlterField(
            model_name='incometax',
            name='effective_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryprocess', verbose_name='生效薪酬表'),
        ),
        migrations.AlterField(
            model_name='salaryadjustment',
            name='effective_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryprocess', verbose_name='生效薪酬表'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='effective_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryprocess', verbose_name='生效薪酬表'),
        ),
        migrations.DeleteModel(
            name='InputPart',
        ),
    ]
