# Generated by Django 5.0.6 on 2024-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0017_salaryadjustment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_work_days',
            field=models.IntegerField(null=True, verbose_name='全勤天数'),
        ),
    ]
